### ISSUE TITLE
在使用火狐浏览器打开项目的时候出现问题如下已拦截跨源请求：同源策略禁止读取位于 http://127.0.0.1:8080/admin/userLogin 的远程资源。

### ISSUE THREAD

**Issue by dk6890** [AftermathJing/CollegesQuestionnaireSystem#1]

**Comment by dk6890** [comment]
![Uploading question.png…]()

**Comment by AftermathJing** [comment]
I am already aware of the issue you raised. It should be an issue with your deployment of the project. Please refer to the Maven and Config files of the project for details.If it has not been resolved yet, please provide more details.

**Comment by dk6890** [comment]
I figured it out. Thank you!!
